version: '3'
services:
    nginx:
        container_name: nginx
        build: ./docker/nginx
        hostname: site.loc
        volumes:
            - ./:/var/www
        ports:
            - '80:80'
        depends_on:
            - php-fpm

    php-fpm:
        container_name: php
        build: ./docker/php-fpm
        volumes:
            - ./:/var/www
        depends_on:
            - mysql
        environment:
            - 'DB_PORT=3306'
            - 'DB_HOST=mysql'

    mysql:
        container_name: mysql
        build: ./docker/mysql
        volumes:
            - ./storage/docker/mysql:/var/lib/mysql
        environment:
            - 'MYSQL_ROOT_PASSWORD=123456'
            - 'MYSQL_USER=root'
            - 'MYSQL_PASSWORD=123456'
            - 'MYSQL_DATABASE=dbname'
        ports:
            - '33061:3306'
